# Generated by Django 4.1.13 on 2024-02-28 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_foodcategory_order_restaurant_orderitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='foodCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.foodcategory'),
        ),
    ]
